# Logfile created on 2020-02-11 17:35:33 +0000 by logger.rb/66358
{"severity":"ERROR","time":"2020-02-11T17:35:33.017Z","correlation_id":null,"extra.server":{"os":{"name":"Linux","version":"#24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019","build":"5.0.0-23-generic","kernel_version":"Linux gitlab 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"},"runtime":{"name":"ruby","version":"ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]"}},"exception.class":"Gitlab::Runtime::UnknownProcessError","exception.message":"Failed to identify runtime for process 1123 (bin/rails)","exception.backtrace":["lib/gitlab/runtime.rb:24:in `identify'","config/environment.rb:6:in `\u003ctop (required)\u003e'"]}
